### ISSUE TITLE
Consider using upx to compress native executables

### ISSUE THREAD

**Issue by sdeleuze** [paketo-buildpacks/native-image#59]
While discussing with GraalVM team, they brought to my attention [UPX](https://upx.github.io/), also mentioned in [this blog post](https://medium.com/graalvm/compressed-graalvm-native-images-4d233766a214). It allows to compress very significantly executables, with fast decompression and faster startup than the uncompressed version at least on my personal computer.

I tried it on the typical [`webmvc-tomcat`](https://github.com/spring-projects-experimental/spring-native/tree/master/samples/webmvc-tomcat) sample of [Spring Native](https://github.com/spring-projects-experimental/spring-native), the result are kind of mind blowing, since **it allows to turn a `50M` Spring Boot + Spring MVC + Tomcat + Jackson native executable into a `14M` one**!

```
15:36 $ upx -7 -k target/webmvc-tomcat
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX git-d7ba31+ Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
  50265544 ->  14983784   29.81%   linux/amd64   webmvc-tomcat                 

Packed 1 file.
✔ ~/workspace/spring-native/samples/webmvc-tomcat
15:36 $ exa -l target/webmvc-tomcat*
.rwxr-xr-x 14M seb 17 Mar 15:28 target/webmvc-tomcat
.rw-r--r-- 15M seb 17 Mar 15:28 target/webmvc-tomcat-0.0.1-SNAPSHOT-exec.jar
.rw-r--r-- 30k seb 17 Mar 15:28 target/webmvc-tomcat-0.0.1-SNAPSHOT.jar
.rwxr-xr-x 50M seb 17 Mar 15:28 target/webmvc-tomcat.~
✔ ~/workspace/spring-native/samples/webmvc-tomcat
15:36 $ target/webmvc-tomcat.~ 
2021-03-17 15:37:16.605  INFO 75719 --- [           main] o.s.nativex.NativeListener               : This application is bootstrapped with code generated with Spring AOT

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::       (v2.4.4-SNAPSHOT)

2021-03-17 15:37:16.646  INFO 75719 --- [           main] com.example.webmvc.WebmvcApplication     : Started WebmvcApplication in 0.046 seconds (JVM running for 0.047)

✘-INT ~/workspace/spring-native/samples/webmvc-tomcat
15:37 $ target/webmvc-tomcat
2021-03-17 15:37:22.492  INFO 75777 --- [           main] o.s.nativex.NativeListener               : This application is bootstrapped with code generated with Spring AOT

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::       (v2.4.4-SNAPSHOT)

2021-03-17 15:37:22.513  INFO 75777 --- [           main] com.example.webmvc.WebmvcApplication     : Started WebmvcApplication in 0.023 seconds (JVM running for 0.024)
```
I guess less IO needed allows faster startup despite the decompression.

**Comment by dmikusa-pivotal** [comment]
I definitely want to do this.

The question in my mind is how to get the `upx` binary for the buildpack. It could be installed by the buildpack, it could be installed by a dedicated buildpack or it could be part of the build image. I have a suspicion that other buildpacks may want to use this as well, so the second or third options are probably best.

I'm asking around with some of the other buildpack authors to see if they would be interested in a more general solution. I think using it with Go and possibly Rust buildpacks might be helpful also, so I'm betting others will be interested. When I get this nailed down, I'll make sure to get `npx` compression into the buildpack. 

Question for those interested:

How do you feel about this being enabled by default? So native-image would by default compress the binary, with an option to disable/skip compression. That's what I'm leaning towards since there seems to be little downside except for a bit of a longer build time. Please let me know if you feel differently.

Thanks

**Comment by jamesward** [comment]
Compression by default makes sense to me. The smaller container image the better. :)

**Comment by sdeleuze** [comment]
Yeah +1 for this to be the default behavior.

**Comment by dmikusa-pivotal** [comment]
Resolved with: https://github.com/paketo-buildpacks/native-image/pull/78

I ended up not having compression be the default because with compression there are caveats (there are also multiple types, so at the moment you need to select the one that works best for you). I'm optimistic that when the issue around `upx` and M1 Macs has been resolved, we can revisit and perhaps make that default & compress by default.
